apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciph-app-deployment
spec:
  selector:
    matchLabels:
      app: ciph-app
  replicas:  {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ciph-app
    spec:
      containers:
       - name: ciph-app-container1
         securityContext:
           privileged: false
         image: ciph_app:{{ .Values.tag }}
         resources:
           requests:
             memory: "1Gi"
             hugepages-1Gi: 1Gi
           limits:
             memory: "1Gi"
             hugepages-1Gi: 1Gi
         volumeMounts:
           - name: hugepage
             mountPath: /hugepages
           - name: varciphapp
             mountPath: /var/ciph_app
             readOnly: false
      volumes:
       - name: hugepage
         emptyDir:
           medium: HugePages
       - name: varciphapp
         hostPath:
           path: "/var/ciph_app"

