apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciph-app-test-deployment
spec:
  selector:
    matchLabels:
      app: ciph-app-test
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ciph-app-test
    spec:
      containers:
       - name: ciph-app-test-container1
         securityContext:
           privileged: false
         image: ciph_app_test:{{ .Values.tag }}
         volumeMounts:
           - name: varciphapp
             mountPath: /var/ciph_app
             readOnly: false
      volumes:
       - name: varciphapp
         hostPath:
           path: "/var/ciph_app"
