apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciph-app-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: ciph-app
  replicas:  {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ciph-app
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
       - name: ciph-app-container1
         securityContext:
           privileged: true
         image: {{ .Values.repository }}:{{ .Values.tag }}
         resources:
           requests:
             memory: "1Gi"
             hugepages-1Gi: 1Gi
           limits:
             memory: "1Gi"
             hugepages-1Gi: 1Gi
         volumeMounts:
           - name: hugepage
             mountPath: /hugepages
           - name: varciphappsock
             mountPath: /var/ciph_app
             readOnly: false
           - name: varciphapplog
             mountPath: /var/log
             readOnly: false
      volumes:
       - name: hugepage
         emptyDir:
           medium: HugePages
       - name: varciphappsock
         hostPath:
           path: "/var/ciph_app"
           type: DirectoryOrCreate
       - name: varciphapplog
         hostPath:
           path: "/var/log/ciph_app"
           type: DirectoryOrCreate
