apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciph-app-test-deployment
spec:
  selector:
    matchLabels:
      app: ciph-app-test
  replicas: 1
  template:
    metadata:
      labels:
        app: ciph-app-test
    spec:
      containers:
       - name: ciph-app-test-container1
         securityContext:
           privileged: false
           capabilities:
             add:
               - SYS_ADMIN
               - IPC_LOCK
               - SYS_NICE
         image: ciph_app_test:v1.3.4
         volumeMounts:
           - name: varciphapp
             mountPath: /var/ciph_app
             readOnly: false
      volumes:
       - name: varciphapp
         hostPath:
           path: "/var/ciph_app"
