apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciph-app-test-deployment
spec:
  selector:
    matchLabels:
      app: ciph-app-test
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ciph-app-test
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
       - name: ciph-app-test-container1
         securityContext:
           privileged: false
         image: {{ .Values.repository }}:{{ .Values.tag }}
         workingDir: /home/ciph_app_test
         command: ["taskset"]
         args: ["0x4", "./ciph_app_test"]
         volumeMounts:
           - name: varciphapp
             mountPath: /var/ciph_app
             readOnly: false
      volumes:
       - name: varciphapp
         hostPath:
           path: "/var/ciph_app"
